services:
  reports-viewer:
    build: .
    container_name: python-server
    ports:
      - "80:5000"  # Maps port 5000 of the container to port 80 of the host
    volumes:
      - ./uploads:/app/uploads  # Mounts folder `uploads` ouside the container
      - .:/app  # Mounts the current directory of the project
    environment:
      FLASK_ENV: production
    restart: always # Always restart the container if it stops
